"""Indicator package: registry + convenient re-exports."""

from __future__ import annotations

from typing import Any, Callable, Dict, List

from . import core, momentum, patterns, trend, volatility, volume
from .core import (
    alma,
    atr,
    crossover,
    dema,
    donchian,
    ema,
    hma,
    kama,
    keltner,
    last_defined,
    macd,
    momentum as momentum_line,
    natr,
    pivot_points,
    ppo,
    rma,
    roc,
    rsi,
    sma,
    smma,
    stoch_rsi,
    tema,
    true_range_series,
    tsi,
    volatility_ratio,
    vwma,
    wma,
)
from .momentum import (
    awesome_oscillator,
    cci,
    elder_ray,
    mfi,
    psychological_line,
    stochastic,
    ultimate_oscillator,
    williams_r,
)
from .trend import (
    adx,
    aroon,
    chande_momentum_oscillator,
    ichimoku,
    linear_regression_channel,
    linear_regression_slope,
    mass_index,
    psar,
    supertrend,
    trend_intensity_index,
    vortex,
)
from .volatility import (
    bandwidth,
    bollinger_bands,
    chaikin_volatility,
    ewma_volatility,
    garch_11,
    historical_volatility,
    realized_range_volatility,
    squeeze_momentum,
    ulcer_index,
    vol_percentile,
)
from .volume import (
    accumulation_distribution,
    chaikin_money_flow,
    ease_of_movement,
    force_index,
    obv,
    vwap,
)
from .divergence import (
    detect_divergence,
    divergence_score,
    find_pivots,
    last_divergence,
)
from .orderflow import (
    TickFlow,
    VolumeProfile,
    cumulative_delta,
    delta_divergence,
    tick_imbalance,
)

INDICATOR_REGISTRY: Dict[str, Callable[..., Any]] = {
    "sma": sma,
    "ema": ema,
    "wma": wma,
    "rma": rma,
    "smma": smma,
    "dema": dema,
    "tema": tema,
    "hma": hma,
    "kama": kama,
    "alma": alma,
    "vwma": vwma,
    "rsi": rsi,
    "stoch_rsi": stoch_rsi,
    "macd": macd,
    "ppo": ppo,
    "roc": roc,
    "tsi": tsi,
    "atr": atr,
    "natr": natr,
    "adx": adx,
    "supertrend": supertrend,
    "psar": psar,
    "ichimoku": ichimoku,
    "stochastic": stochastic,
    "cci": cci,
    "mfi": mfi,
    "williams_r": williams_r,
    "ultimate_oscillator": ultimate_oscillator,
    "awesome_oscillator": awesome_oscillator,
    "bollinger_bands": bollinger_bands,
    "bandwidth": bandwidth,
    "squeeze_momentum": squeeze_momentum,
    "historical_volatility": historical_volatility,
    "ewma_volatility": ewma_volatility,
    "garch_11": garch_11,
    "ulcer_index": ulcer_index,
    "obv": obv,
    "vwap": vwap,
    "chaikin_money_flow": chaikin_money_flow,
    "force_index": force_index,
    "donchian": donchian,
    "keltner": keltner,
    "linear_regression_channel": linear_regression_channel,
    "aroon": aroon,
    "vortex": vortex,
    "find_pivots": find_pivots,
    "detect_divergence": detect_divergence,
    "last_divergence": last_divergence,
    "divergence_score": divergence_score,
    "tick_imbalance": tick_imbalance,
    "cumulative_delta": cumulative_delta,
    "delta_divergence": delta_divergence,
    "VolumeProfile": VolumeProfile,
    "TickFlow": TickFlow,
}


def list_indicators() -> List[str]:
    return sorted(INDICATOR_REGISTRY)


def get(name: str) -> Callable[..., Any]:
    try:
        return INDICATOR_REGISTRY[name]
    except KeyError as exc:
        raise KeyError(f"unknown indicator {name!r}") from exc


__all__ = [
    "core",
    "trend",
    "momentum",
    "volatility",
    "volume",
    "patterns",
    "INDICATOR_REGISTRY",
    "list_indicators",
    "get",
    "sma",
    "ema",
    "wma",
    "rma",
    "smma",
    "dema",
    "tema",
    "hma",
    "kama",
    "alma",
    "vwma",
    "rsi",
    "stoch_rsi",
    "macd",
    "ppo",
    "roc",
    "momentum_line",
    "tsi",
    "atr",
    "natr",
    "true_range_series",
    "volatility_ratio",
    "donchian",
    "keltner",
    "pivot_points",
    "crossover",
    "last_defined",
    "adx",
    "supertrend",
    "psar",
    "ichimoku",
    "linear_regression_channel",
    "linear_regression_slope",
    "aroon",
    "vortex",
    "chande_momentum_oscillator",
    "mass_index",
    "trend_intensity_index",
    "stochastic",
    "cci",
    "mfi",
    "williams_r",
    "ultimate_oscillator",
    "awesome_oscillator",
    "elder_ray",
    "psychological_line",
    "bollinger_bands",
    "bandwidth",
    "squeeze_momentum",
    "historical_volatility",
    "ewma_volatility",
    "garch_11",
    "chaikin_volatility",
    "ulcer_index",
    "realized_range_volatility",
    "vol_percentile",
    "obv",
    "vwap",
    "chaikin_money_flow",
    "accumulation_distribution",
    "force_index",
    "ease_of_movement",
]
